# ---------------------------------

# fira
# font_family      Fira Code
# font_size 13.0
# modify_font underline_position 5
# modify_font underline_thickness 170%
# modify_font cell_height 2px
# modify_font baseline 2
# fira end

# ---------------------------------

# jetbrains
font_family      JetBrains Mono NL Bold
font_size 13.0
modify_font underline_position 2
modify_font underline_thickness 170%
modify_font cell_height 6px
modify_font baseline 1
# jetbrains end

# ---------------------------------

cursor #7bb98b
cursor_shape block
cursor_blink_interval 0
# 关闭光标动画
cursor_trail 0 
# 禁止 shell integration 自动切换光标样式
shell_integration no-cursor

# 窗口布局
enabled_layouts tall:bias=50

window_padding_width 0

placement_strategy center
# 窗口title
hide_window_decorations yes 

active_tab_background   cyan
map ctrl+tab no_op
map ctrl+shift+tab no_op

allow_remote_control yes
listen_on unix:/tmp/locator_vim_kitty--

shell_integration enabled
action_alias kitty_scrollback_nvim kitten ~/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py
map kitty_mod+n kitty_scrollback_nvim

map ctrl+y kitten smart_scroll.py scroll_page_up   ctrl+y
map ctrl+e kitten smart_scroll.py scroll_page_down ctrl+e
