include vscode-theme.conf

# ---------------------------------
# fira
# font_family      Fira Code
# font_size 13.0
# modify_font underline_position 5
# modify_font underline_thickness 170%
# modify_font cell_height 2px
# modify_font baseline 2
# fira end
# ---------------------------------
# jetbrains
font_family      JetBrains Mono NL Bold
font_size 13.0
modify_font underline_position 2
modify_font underline_thickness 170%
modify_font cell_height 6px
modify_font baseline 1
# jetbrains end
# ---------------------------------
cursor #7bb98b
cursor_shape beam
cursor_blink_interval 0
# 关闭光标动画
cursor_trail 0 

# 窗口布局
enabled_layouts grid 

window_padding_width 0

window_border_width 1pt
active_border_color #7bb98b
inactive_border_color #444444

placement_strategy center
# 窗口title
hide_window_decorations yes 

map ctrl+tab no_op
map ctrl+shift+tab no_op

# Ctrl+u 挂起进程
map ctrl+z no_op
map ctrl+u send_text all \x1a

# neovim 历史文件搜索，禁用清屏
map cmd+l no_op
# 清除屏幕和 scrollback
map cmd+k combine : clear_terminal scroll active : clear_terminal scrollback active

map cmd+1 no_op 
map cmd+2 no_op 
map cmd+3 no_op 
map cmd+4 no_op 

map f1 launch --cwd=current
map f2 launch --cwd=current --type=tab

allow_remote_control yes
listen_on unix:/tmp/locator_vim_kitty--

shell_integration enabled
action_alias kitty_scrollback_nvim kitten ~/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py
map cmd+y kitty_scrollback_nvim

tab_title_template "{fmt.noitalic}{fmt.fg.tab}[{index}] {title}"
active_tab_title_template "{fmt.noitalic}{fmt.fg.tab}[{index}] {title}"

tab_bar_min_tabs 1
tab_bar_style powerline
tab_bar_background #1e1e1e
inactive_tab_background #252526
inactive_tab_foreground #a0a0a0

# tab 索引
map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9


# Ctrl+; → 发送 CSI u 编码 (;=59, Ctrl=5)
map ctrl+semicolon send_text all \x1b[59;5u

# resize window
window_resize_step_cells 1
window_resize_step_lines 1

# vim-kitty-navigator
map shift+left  kitten pass_keys.py left   shift+left                                                                                                                                         
map shift+down  kitten pass_keys.py bottom shift+down                                                                                                                                       
map shift+up    kitten pass_keys.py top    shift+up                                                                                                                                              
map shift+right kitten pass_keys.py right  shift+right

