matches:
  - trigger: 'log;'
    replace: 'console.log("$|$")'

  - trigger: 'err;'
    replace: 'console.error("$|$")'

  - trigger: 'trace;'
    replace: 'console.trace($|$)'

  - trigger: 'profile;'
    replace: |-
      console.profile("time");
      console.profileEnd("time");

  - trigger: 'time;'
    replace: |-
      console.time("time");
      console.timeEnd("time");

  - trigger: 'cc;'
    replace: 'contentview/index.vue'

  - trigger: 'ck;'
    replace: '整体再检查一遍，确保没有遗漏修改和遗漏修改'

  - trigger: 'tt;'
    replace: "/timeline\n"
