set -sg escape-time 10
set -s allow-passthrough on
setw -g mode-keys vi
set -g history-limit 30000
set -g mouse on

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

